### PR TITLE
WORKPLACE HAZARDS (1/2)

### PR DESCRIPTION
**Pull request by Sascha-T**
Merge the first 3 additions (new damage sources) into Main.
Currently a draft.
Progress reflected in #14

### CODE REVIEW

**Comment by rhysdh540** [comment]
"looks" good to me (I haven't looked at it)

**Comment by rhysdh540** [comment]
it compiles, so that's good enough

**Review by Tors-0 — APPROVED** [review]
ez dubs, merge ok

**Comment by Sascha-T** [comment]
let's gooooooo

**Comment by Sascha-T** [comment]
time to mess up all the people working on Main right now with uncommitted unpushed changes

**Comment by JR1811** [comment]
> time to mess up all the people working on Main right now with uncommitted unpushed changes

thats why you shouldnt work on main... just merge into it :]

If in doubt... Blame the ore gen people 😈

**Pull request merged**
