### PR TITLE
Sanity organization

### PR DESCRIPTION
**Pull request by techno-sam**
Re-organize everything to follow a consistent and convenient structure (taken from Steam 'n Rails)

### CODE REVIEW

**Review by IThundxr — APPROVED** [review]
LGTM! :)

**Comment by Sascha-T** [comment]
Will we have to re-merge #24

**Review by Sascha-T — APPROVED** [review]
**LGTM ASAP!!!!!!!** :DD

**Comment by IThundxr** [comment]
we dont wait for checks :3

**Pull request merged**
