### PR TITLE
Feat/oregen #5

### PR DESCRIPTION
**Pull request by Tors-0**
#5

### CODE REVIEW

**Comment by Sascha-T** [comment]
```
Caused by: java.lang.NoClassDefFoundError: com/calamityteam/calamity/base/world/feature/fabric/CalamityFeaturesImpl
	at com.calamityteam.calamity.base.world.feature.CalamityFeatures.addFeaturesToWorldgen(CalamityFeatures.java)
	at com.calamityteam.calamity.base.world.feature.CalamityFeatures.register(CalamityFeatures.java:39)
	at com.calamityteam.calamity.CreateCalamity.init(CreateCalamity.java:28)
	at com.calamityteam.calamity.fabric.CreateCalamityFabric.onInitialize(CreateCalamityFabric.java:10)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 10 more
	```

**Comment by Sascha-T** [comment]
wait i was on an old commit sec

**Comment by Sascha-T** [comment]
i lied, i was not??

**Comment by Sascha-T** [comment]
Untextured but that's because of missing data generator?

**Review by Sascha-T — CHANGES_REQUESTED** [review]
Missing data generators and wonky project structure will be fixed by Slimeist.
Maybe add actual block/item models for the brass ore though?

**Comment by Sascha-T** [comment]
Also ore-gen doesn't appear to work on Forge, not sure why?
Fabric works mostly as expected.

**Comment by Tors-0** [comment]
@Sascha-T missing json models will be added by datagenerators when added

**Comment by Sascha-T** [comment]
is that a thing they can do?? wild okay

**Review by Sascha-T — APPROVED** [review]
chat i lied, all is well, world peace is restored once more by NETHER BRASS ORE

**Comment by Sascha-T** [comment]
LGTM

**Comment by Tors-0** [comment]
missing texture is bc there's no model

**Pull request merged**
